function [VarName1,VarName2] = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [VarName1,VarName2] = IMPORTFILE(FILE) reads data from the first
%   worksheet in the Microsoft Excel spreadsheet file named FILE and
%   returns the data as column vectors.
%
%   [VarName1,VarName2] = IMPORTFILE(FILE,SHEET) reads from the specified
%   worksheet.
%
%   [VarName1,VarName2] = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from
%   the specified worksheet for the specified row interval(s). Specify
%   STARTROW and ENDROW as a pair of scalars or vectors of matching size
%   for dis-contiguous row intervals. To read to the end of the file
%   specify an ENDROW of inf.%
% Example:
%   [VarName1,VarName2] = importfile('Rocket_Positionv_v_Speed_v2.xlsx','Export Data',1,354);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/02/11 13:28:56

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 354;
end

%% Import the data
data = xlsread(workbookFile, sheetName, sprintf('A%d:B%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    tmpDataBlock = xlsread(workbookFile, sheetName, sprintf('A%d:B%d',startRow(block),endRow(block)));
    data = [data;tmpDataBlock]; %#ok<AGROW>
end

%% Allocate imported array to column variable names
VarName1 = data(:,1);
VarName2 = data(:,2);

